name: Update Native-Dark

on:
  push:
    tags:
      - 'publish*'

jobs:
  update-native-dark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout roam-search-plus repository
        uses: actions/checkout@v2
        with:
          repository: dive2Pro/roam-search-plus
      - name: Checkout roam-depot repository
        uses: actions/checkout@v2
        with:
          repository: Roam-Research/roam-depot
          ref: main
          token: ${{ secrets.PAT }}

      - name: Delete Native-Dark branch if exists
        run: |
          git branch -D Native-Dark || true
          git fetch --all
          git branch -D Native-Dark || true

      - name: Create Native-Dark branch from main
        run: |
          git checkout -b Native-Dark origin/main

      - name: Update roam-native-dark.json
        run: |
          sed -i 's/"source_commit": ".*/"source_commit": "'"$GITHUB_SHA"'",/g' extensions/hyc/roam-native-dark.json

      - name: Commit and Push changes
        run: |
          git config --global user.name "hyc"
          git config --global user.email "toylucklebo@gmail.com"
          git add extensions/hyc/roam-native-dark.json
          git commit -m "Update source_commit to $GITHUB_SHA"
          git push -u origin Native-Dark
