name: Update Native Dark
on:
  push:
    tags:
      - 'publish*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.name "hyc"
          git config --global user.email "toylucklebo@gmail.com"
      - name: Checkout roam-depot repository
        uses: actions/checkout@v2
        with:
          repository: dive2Pro/roam-depot
          ref: main
          token: ${{ secrets.PAT }}
      - name: Delete and checkout Native-Dark branch
        run: |
          git push --delete origin Native-Dark
          git checkout -b Native-Dark origin/main
      - name: Modify JSON file
        run: |
          sed -i 's/"source_commit": "[^"]*"/"source_commit": "'"$GITHUB_SHA"'"/' extensions/hyc/roam-native-dark.json
          git add extensions/hyc/roam-native-dark.json
          git commit -m "Update Native Dark to $GITHUB_SHA"
          git push -u origin Native-Dark
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'Update Native Dark'
          title: 'Update Native Dark'
          body: 'This is a pull request created by a GitHub Action.'
