name: Update Native-Dark extension
on:
  push:
    tags:
      - 'publish*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout roam-search-plus repository
        uses: actions/checkout@v2
        with:
          repository: dive2Pro/roam-search-plus
      - name: Checkout roam-depot repository
        uses: actions/checkout@v2
        with:
          repository: dive2Pro/roam-depot
          ref: Native-Dark
      - name: Update Native-Dark extension
        run: |
          sed -i 's/"source_commit": "[^"]*"/"source_commit": "${{ github.sha }}"/' extensions/hyc/roam-native-dark.json
      - name: Commit and push changes
        run: |
          git config --global user.email "hyc"
          git config --global user.name "toylucklebo@gmail.com"
          git commit -am "Update source_commit field to ${GITHUB_SHA}"
          git push
