name: Update Roam Depot Source Commit
on:
  push:
    tags:
      - 'publish*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update source_commit field
        run: |
          sed -i "s/\"source_commit\": \".*\"/\"source_commit\": \"${GITHUB_SHA}\"/" extensions/hyc/roam-native-dark.json
      - name: Commit and push changes
        run: |
          git config --global user.name 'hyc'
          git config --global user.email 'toylucklebo@gmail.com'
          git add extensions/hyc/roam-native-dark.json
          git commit -m "Update source_commit field"
          git push origin Native-Dark
